services:
  services_frontend:
    build:
      context: ./app_frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    volumes:
      - ./app_frontend:/app
      - ./app_frontend/instance:/app/instance
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PHONE=${ADMIN_PHONE}
      - ADMIN_ADDRESS=${ADMIN_ADDRESS}
      - BUSINESS_CONFIG_PATH=${BUSINESS_CONFIG_PATH}
      # - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      # - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ngrok http services_frontend:5000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}  
      # Optional additional environment variables:
      # - NGROK_SUBDOMAIN=${NGROK_SUBDOMAIN}
      # - NGROK_HOSTNAME=${NGROK_HOSTNAME}
      # - NGROK_USERNAME=${NGROK_USERNAME}
      # - NGROK_PASSWORD=${NGROK_PASSWORD}
      # - NGROK_REGION=${NGROK_REGION}
      # - NGROK_HEADER=${NGROK_HEADER}
    depends_on:
      - services_frontend