version: '3'
services:
  frontend:
    build:
      context: https://github.com/Hotschmoe/strongs-simple-services
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  frontend-local:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    volumes:
      - .:/app