version: '3'
services:
  services_frontend:
    build:
      context: ./app_frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    volumes:
      - ./app_frontend:/app
    environment:
      - FLASK_ENV=development
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpassword
      - ADMIN_NAME=Admin User
      - ADMIN_PHONE=1234567890
      - ADMIN_ADDRESS=123 Admin St, Admin City
      # - STRIPE_SECRET_KEY=your_stripe_secret_key
      # - STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key

#   services_database:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=laundry_service
#       - POSTGRES_USER=yourusername
#       - POSTGRES_PASSWORD=your_password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: